# Generated by Django 4.2.7 on 2026-01-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(help_text='Descriptive name for this API key', max_length=100),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='rate_limit',
            field=models.PositiveIntegerField(default=100, help_text='Maximum requests per hour'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='apikey',
            table=None,
        ),
    ]
